//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowTenant1.SalaryDetails {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaryDetails.ISalaryDetails")]
    public interface ISalaryDetails {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryDetails/GetClientSalary", ReplyAction="http://tempuri.org/ISalaryDetails/GetClientSalaryResponse")]
        WorkflowTenant1.SalaryDetails.GetClientSalaryResponse GetClientSalary(WorkflowTenant1.SalaryDetails.GetClientSalaryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientSalary", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClientSalaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int clientId;
        
        public GetClientSalaryRequest() {
        }
        
        public GetClientSalaryRequest(int clientId) {
            this.clientId = clientId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientSalaryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClientSalaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal GetClientSalaryResult;
        
        public GetClientSalaryResponse() {
        }
        
        public GetClientSalaryResponse(decimal GetClientSalaryResult) {
            this.GetClientSalaryResult = GetClientSalaryResult;
        }
    }
}
