//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWorkflows.IncomeTax {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IncomeTax.IIncomeTax")]
    public interface IIncomeTax {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncomeTax/VerifyTax", ReplyAction="http://tempuri.org/IIncomeTax/VerifyTaxResponse")]
        CoreWorkflows.IncomeTax.VerifyTaxResponse VerifyTax(CoreWorkflows.IncomeTax.VerifyTaxRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyTax", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyTaxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int clientId;
        
        public VerifyTaxRequest() {
        }
        
        public VerifyTaxRequest(int clientId) {
            this.clientId = clientId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyTaxResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyTaxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string VerifyTaxResult;
        
        public VerifyTaxResponse() {
        }
        
        public VerifyTaxResponse(string VerifyTaxResult) {
            this.VerifyTaxResult = VerifyTaxResult;
        }
    }
}
