//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutlitenancyClient.FinancialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacilityRequest", Namespace="http://schemas.datacontract.org/2004/07/DataContractLibrary")]
    [System.SerializableAttribute()]
    public partial class FacilityRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MutlitenancyClient.FinancialService.Client CurrentClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FacilityAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaciliytIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaciliytTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MutlitenancyClient.FinancialService.Client CurrentClient {
            get {
                return this.CurrentClientField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentClientField, value) != true)) {
                    this.CurrentClientField = value;
                    this.RaisePropertyChanged("CurrentClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FacilityAmount {
            get {
                return this.FacilityAmountField;
            }
            set {
                if ((this.FacilityAmountField.Equals(value) != true)) {
                    this.FacilityAmountField = value;
                    this.RaisePropertyChanged("FacilityAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaciliytId {
            get {
                return this.FaciliytIdField;
            }
            set {
                if ((this.FaciliytIdField.Equals(value) != true)) {
                    this.FaciliytIdField = value;
                    this.RaisePropertyChanged("FaciliytId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaciliytType {
            get {
                return this.FaciliytTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FaciliytTypeField, value) != true)) {
                    this.FaciliytTypeField = value;
                    this.RaisePropertyChanged("FaciliytType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/DataContractLibrary")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinancialService.FinancialService")]
    public interface FinancialService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/FinancialService/CreateFacility")]
        void CreateFacility(MutlitenancyClient.FinancialService.FacilityRequest FacilityRequest);
        
        // CODEGEN: Generating message contract since the operation UpdateFacility is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/FinancialService/UpdateFacility")]
        void UpdateFacility(MutlitenancyClient.FinancialService.UpdateFacility request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFacility {
        
        public UpdateFacility() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinancialServiceChannel : MutlitenancyClient.FinancialService.FinancialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialServiceClient : System.ServiceModel.ClientBase<MutlitenancyClient.FinancialService.FinancialService>, MutlitenancyClient.FinancialService.FinancialService {
        
        public FinancialServiceClient() {
        }
        
        public FinancialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateFacility(MutlitenancyClient.FinancialService.FacilityRequest FacilityRequest) {
            base.Channel.CreateFacility(FacilityRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MutlitenancyClient.FinancialService.FinancialService.UpdateFacility(MutlitenancyClient.FinancialService.UpdateFacility request) {
            base.Channel.UpdateFacility(request);
        }
        
        public void UpdateFacility() {
            MutlitenancyClient.FinancialService.UpdateFacility inValue = new MutlitenancyClient.FinancialService.UpdateFacility();
            ((MutlitenancyClient.FinancialService.FinancialService)(this)).UpdateFacility(inValue);
        }
    }
}
