//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSP.ContributionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContributionService.IContributionService")]
    public interface IContributionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/ContributeOnline", ReplyAction="http://tempuri.org/IContributionService/ContributeOnlineResponse")]
        DataContractLibrary.ValidationResponse ContributeOnline(int uniqueId, string product, int units);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/ChangeSchemePreference", ReplyAction="http://tempuri.org/IContributionService/ChangeSchemePreferenceResponse")]
        DataContractLibrary.ValidationResponse ChangeSchemePreference(int uniqueId, int newSchemePreferenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContributionService/ChangeFundManagerName", ReplyAction="http://tempuri.org/IContributionService/ChangeFundManagerNameResponse")]
        DataContractLibrary.ValidationResponse ChangeFundManagerName(int uniqueId, string fundManagerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContributionServiceChannel : DSP.ContributionService.IContributionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContributionServiceClient : System.ServiceModel.ClientBase<DSP.ContributionService.IContributionService>, DSP.ContributionService.IContributionService {
        
        public ContributionServiceClient() {
        }
        
        public ContributionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContributionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContributionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContributionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataContractLibrary.ValidationResponse ContributeOnline(int uniqueId, string product, int units) {
            return base.Channel.ContributeOnline(uniqueId, product, units);
        }
        
        public DataContractLibrary.ValidationResponse ChangeSchemePreference(int uniqueId, int newSchemePreferenceId) {
            return base.Channel.ChangeSchemePreference(uniqueId, newSchemePreferenceId);
        }
        
        public DataContractLibrary.ValidationResponse ChangeFundManagerName(int uniqueId, string fundManagerName) {
            return base.Channel.ChangeFundManagerName(uniqueId, fundManagerName);
        }
    }
}
