//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int accountNumber { get; set; }
        public string bankBranch { get; set; }
        public string bankName { get; set; }
        public string address { get; set; }
        public int ifscCode { get; set; }
        public int uniqueId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
