//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldingSummary
    {
        public int HoldingSummaryId { get; set; }
        public int UniqueId { get; set; }
        public string HoldingSchemeName { get; set; }
        public Nullable<decimal> TotalUnits { get; set; }
        public Nullable<decimal> Nav { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
