//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.BankInfoes = new HashSet<BankInfo>();
            this.HoldingSummaries = new HashSet<HoldingSummary>();
            this.SchemeInfoes = new HashSet<SchemeInfo>();
            this.TransactionSummaries = new HashSet<TransactionSummary>();
        }
    
        public int uniqueId { get; set; }
        public string fullName { get; set; }
        public string fathersName { get; set; }
        public string mothersName { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string gender { get; set; }
        public string nationality { get; set; }
        public bool isKycDone { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public Nullable<int> pinCode { get; set; }
        public string mobile { get; set; }
    
        public virtual ICollection<BankInfo> BankInfoes { get; set; }
        public virtual ICollection<HoldingSummary> HoldingSummaries { get; set; }
        public virtual ICollection<SchemeInfo> SchemeInfoes { get; set; }
        public virtual ICollection<TransactionSummary> TransactionSummaries { get; set; }
    }
}
