//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutlitenancyClient.FacilityServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacilityRequest", Namespace="http://schemas.datacontract.org/2004/07/DataContractLibrary")]
    [System.SerializableAttribute()]
    public partial class FacilityRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MutlitenancyClient.FacilityServiceClient.Client CurrentClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FacilityAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaciliytIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaciliytTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MutlitenancyClient.FacilityServiceClient.Client CurrentClient {
            get {
                return this.CurrentClientField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentClientField, value) != true)) {
                    this.CurrentClientField = value;
                    this.RaisePropertyChanged("CurrentClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FacilityAmount {
            get {
                return this.FacilityAmountField;
            }
            set {
                if ((this.FacilityAmountField.Equals(value) != true)) {
                    this.FacilityAmountField = value;
                    this.RaisePropertyChanged("FacilityAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaciliytId {
            get {
                return this.FaciliytIdField;
            }
            set {
                if ((this.FaciliytIdField.Equals(value) != true)) {
                    this.FaciliytIdField = value;
                    this.RaisePropertyChanged("FaciliytId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaciliytType {
            get {
                return this.FaciliytTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FaciliytTypeField, value) != true)) {
                    this.FaciliytTypeField = value;
                    this.RaisePropertyChanged("FaciliytType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/DataContractLibrary")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacilityResponse", Namespace="http://schemas.datacontract.org/2004/07/DataContractLibrary")]
    [System.SerializableAttribute()]
    public partial class FacilityResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClientSalaryAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MutlitenancyClient.FacilityServiceClient.Client CurrentClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncomeTaxStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LoanAmountApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VerifiedAmontBenchMarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClientSalaryAmount {
            get {
                return this.ClientSalaryAmountField;
            }
            set {
                if ((this.ClientSalaryAmountField.Equals(value) != true)) {
                    this.ClientSalaryAmountField = value;
                    this.RaisePropertyChanged("ClientSalaryAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MutlitenancyClient.FacilityServiceClient.Client CurrentClient {
            get {
                return this.CurrentClientField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentClientField, value) != true)) {
                    this.CurrentClientField = value;
                    this.RaisePropertyChanged("CurrentClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncomeTaxStatus {
            get {
                return this.IncomeTaxStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.IncomeTaxStatusField, value) != true)) {
                    this.IncomeTaxStatusField = value;
                    this.RaisePropertyChanged("IncomeTaxStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LoanAmountApproved {
            get {
                return this.LoanAmountApprovedField;
            }
            set {
                if ((this.LoanAmountApprovedField.Equals(value) != true)) {
                    this.LoanAmountApprovedField = value;
                    this.RaisePropertyChanged("LoanAmountApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanStatus {
            get {
                return this.LoanStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanStatusField, value) != true)) {
                    this.LoanStatusField = value;
                    this.RaisePropertyChanged("LoanStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VerifiedAmontBenchMark {
            get {
                return this.VerifiedAmontBenchMarkField;
            }
            set {
                if ((this.VerifiedAmontBenchMarkField.Equals(value) != true)) {
                    this.VerifiedAmontBenchMarkField = value;
                    this.RaisePropertyChanged("VerifiedAmontBenchMark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacilityServiceClient.IFacilityService")]
    public interface IFacilityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacilityService/CreateFacility", ReplyAction="http://tempuri.org/IFacilityService/CreateFacilityResponse")]
        MutlitenancyClient.FacilityServiceClient.FacilityResponse CreateFacility(MutlitenancyClient.FacilityServiceClient.FacilityRequest value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacilityService/UpdateFacility", ReplyAction="http://tempuri.org/IFacilityService/UpdateFacilityResponse")]
        MutlitenancyClient.FacilityServiceClient.FacilityResponse UpdateFacility(MutlitenancyClient.FacilityServiceClient.FacilityRequest value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacilityServiceChannel : MutlitenancyClient.FacilityServiceClient.IFacilityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacilityServiceClient : System.ServiceModel.ClientBase<MutlitenancyClient.FacilityServiceClient.IFacilityService>, MutlitenancyClient.FacilityServiceClient.IFacilityService {
        
        public FacilityServiceClient() {
        }
        
        public FacilityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacilityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacilityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacilityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MutlitenancyClient.FacilityServiceClient.FacilityResponse CreateFacility(MutlitenancyClient.FacilityServiceClient.FacilityRequest value) {
            return base.Channel.CreateFacility(value);
        }
        
        public MutlitenancyClient.FacilityServiceClient.FacilityResponse UpdateFacility(MutlitenancyClient.FacilityServiceClient.FacilityRequest value) {
            return base.Channel.UpdateFacility(value);
        }
    }
}
