//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AggregatorSvcService.WithdrawService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResponse", Namespace="http://schemas.datacontract.org/2004/07/DataContractLibrary")]
    [System.SerializableAttribute()]
    public partial class ValidationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationMessage {
            get {
                return this.ValidationMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationMessageField, value) != true)) {
                    this.ValidationMessageField = value;
                    this.RaisePropertyChanged("ValidationMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExitRequestResponse", Namespace="http://schemas.datacontract.org/2004/07/DataContractLibrary")]
    [System.SerializableAttribute()]
    public partial class ExitRequestResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateRaisedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UniqueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRaised {
            get {
                return this.DateRaisedField;
            }
            set {
                if ((this.DateRaisedField.Equals(value) != true)) {
                    this.DateRaisedField = value;
                    this.RaisePropertyChanged("DateRaised");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((this.UniqueIdField.Equals(value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WithdrawService.IWithdrawService")]
    public interface IWithdrawService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWithdrawService/WithdrawT1Amount", ReplyAction="http://tempuri.org/IWithdrawService/WithdrawT1AmountResponse")]
        AggregatorSvcService.WithdrawService.ValidationResponse WithdrawT1Amount(int uniqueId, string product, decimal withdrawPercent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWithdrawService/ExitRequest", ReplyAction="http://tempuri.org/IWithdrawService/ExitRequestResponse")]
        AggregatorSvcService.WithdrawService.ValidationResponse ExitRequest(int uniqueId, string schemeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWithdrawService/GetExitStatus", ReplyAction="http://tempuri.org/IWithdrawService/GetExitStatusResponse")]
        AggregatorSvcService.WithdrawService.ExitRequestResponse GetExitStatus(int uniqueId, string schemeName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWithdrawServiceChannel : AggregatorSvcService.WithdrawService.IWithdrawService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WithdrawServiceClient : System.ServiceModel.ClientBase<AggregatorSvcService.WithdrawService.IWithdrawService>, AggregatorSvcService.WithdrawService.IWithdrawService {
        
        public WithdrawServiceClient() {
        }
        
        public WithdrawServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WithdrawServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WithdrawServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WithdrawServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AggregatorSvcService.WithdrawService.ValidationResponse WithdrawT1Amount(int uniqueId, string product, decimal withdrawPercent) {
            return base.Channel.WithdrawT1Amount(uniqueId, product, withdrawPercent);
        }
        
        public AggregatorSvcService.WithdrawService.ValidationResponse ExitRequest(int uniqueId, string schemeName) {
            return base.Channel.ExitRequest(uniqueId, schemeName);
        }
        
        public AggregatorSvcService.WithdrawService.ExitRequestResponse GetExitStatus(int uniqueId, string schemeName) {
            return base.Channel.GetExitStatus(uniqueId, schemeName);
        }
    }
}
