//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSP.WithdrawService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WithdrawService.IWithdrawService")]
    public interface IWithdrawService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWithdrawService/WithdrawT1Amount", ReplyAction="http://tempuri.org/IWithdrawService/WithdrawT1AmountResponse")]
        Common.Entities.ValidationResponse WithdrawT1Amount(int uniqueId, string product, decimal withdrawPercent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWithdrawService/ExitRequest", ReplyAction="http://tempuri.org/IWithdrawService/ExitRequestResponse")]
        Common.Entities.ValidationResponse ExitRequest(int uniqueId, string schemeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWithdrawService/GetExitStatus", ReplyAction="http://tempuri.org/IWithdrawService/GetExitStatusResponse")]
        Common.Entities.ExitRequestResponse GetExitStatus(int uniqueId, string schemeName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWithdrawServiceChannel : DSP.WithdrawService.IWithdrawService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WithdrawServiceClient : System.ServiceModel.ClientBase<DSP.WithdrawService.IWithdrawService>, DSP.WithdrawService.IWithdrawService {
        
        public WithdrawServiceClient() {
        }
        
        public WithdrawServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WithdrawServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WithdrawServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WithdrawServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Entities.ValidationResponse WithdrawT1Amount(int uniqueId, string product, decimal withdrawPercent) {
            return base.Channel.WithdrawT1Amount(uniqueId, product, withdrawPercent);
        }
        
        public Common.Entities.ValidationResponse ExitRequest(int uniqueId, string schemeName) {
            return base.Channel.ExitRequest(uniqueId, schemeName);
        }
        
        public Common.Entities.ExitRequestResponse GetExitStatus(int uniqueId, string schemeName) {
            return base.Channel.GetExitStatus(uniqueId, schemeName);
        }
    }
}
