//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowTenant2.FacilityValidation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacilityValidation.IFacilityValidation")]
    public interface IFacilityValidation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacilityValidation/GetFacilityValidationAmountForFaciliytType" +
            "", ReplyAction="http://tempuri.org/IFacilityValidation/GetFacilityValidationAmountForFaciliytType" +
            "Response")]
        WorkflowTenant2.FacilityValidation.GetFacilityValidationAmountForFaciliytTypeResponse GetFacilityValidationAmountForFaciliytType(WorkflowTenant2.FacilityValidation.GetFacilityValidationAmountForFaciliytTypeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFacilityValidationAmountForFaciliytType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFacilityValidationAmountForFaciliytTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string value;
        
        public GetFacilityValidationAmountForFaciliytTypeRequest() {
        }
        
        public GetFacilityValidationAmountForFaciliytTypeRequest(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFacilityValidationAmountForFaciliytTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFacilityValidationAmountForFaciliytTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal GetFacilityValidationAmountForFaciliytTypeResult;
        
        public GetFacilityValidationAmountForFaciliytTypeResponse() {
        }
        
        public GetFacilityValidationAmountForFaciliytTypeResponse(decimal GetFacilityValidationAmountForFaciliytTypeResult) {
            this.GetFacilityValidationAmountForFaciliytTypeResult = GetFacilityValidationAmountForFaciliytTypeResult;
        }
    }
}
