//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuthWebsite.AggregatorSvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AggregatorSvcRef.IAggregatorSvc")]
    public interface IAggregatorSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAggregatorSvc/GetData", ReplyAction="http://tempuri.org/IAggregatorSvc/GetDataResponse")]
        DataContractLibrary.AggregatorResponse GetData(DataContractLibrary.AggregatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAggregatorSvc/AuthenticationMethod", ReplyAction="http://tempuri.org/IAggregatorSvc/AuthenticationMethodResponse")]
        string AuthenticationMethod();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAggregatorSvcChannel : TestAuthWebsite.AggregatorSvcRef.IAggregatorSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AggregatorSvcClient : System.ServiceModel.ClientBase<TestAuthWebsite.AggregatorSvcRef.IAggregatorSvc>, TestAuthWebsite.AggregatorSvcRef.IAggregatorSvc {
        
        public AggregatorSvcClient() {
        }
        
        public AggregatorSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AggregatorSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AggregatorSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AggregatorSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataContractLibrary.AggregatorResponse GetData(DataContractLibrary.AggregatorRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string AuthenticationMethod() {
            return base.Channel.AuthenticationMethod();
        }
    }
}
